export const REQUESTED_FILMS='REQUESTED_FILMS';
export const REQUESTED_FILMS_SUCCEEDED ='REQUESTED_FILMS_SUCCEEDED';
export const REQUESTED_FILMS_FAILED ='REQUESTED_FILMS_FAILED';
export const GET_REQUEST_VALUE ='GET_REQUEST_VALUE';

export const REQUESTED_ONE_FILM='REQUESTED_ONE_FILM';
export const REQUESTED_ONE_FILM_SUCCEEDED ='REQUESTED_ONE_FILM_SUCCEEDED';
export const REQUESTED_ONE_FILM_FAILED ='REQUESTED_ONE_FILM_FAILED';
export const FILM_SORT ='FILM_SORT';
export const CLEAR_FILM_SORT ='CLEAR_FILM_SORT';
