export const REQUESTED_FILM='REQUESTED_FILM';
export const REQUESTED_FILM_SUCCEEDED ='REQUESTED_FILM_SUCCEEDED';
export const REQUESTED_FILM_FAILED ='REQUESTED_FILM_FAILED';
export const GET_REQUEST_VALUE ='GET_REQUEST_VALUE';


