import filter from "./utils/fitler.utils";

describe('utils/fitler.utils', () => {
  describe('fitler.utils', () => {
    const unsortedMockingArray = JSON.parse(`[{"Title":"Rome","Year":"2005–2007","imdbID":"tt0384766","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BYTM4MmU1NWYtNzJjYy00YWFhLThjOGEtZmMxOGI1NzE0NGNiXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg"},{"Title":"To Rome with Love","Year":"2012","imdbID":"tt1859650","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTcwNTg4MDMxM15BMl5BanBnXkFtZTcwNjAzMzY3Nw@@._V1_SX300.jpg"},{"Title":"When in Rome","Year":"2010","imdbID":"tt1185416","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTM0OTQ3MjgzN15BMl5BanBnXkFtZTcwMjMyNzg3Mg@@._V1_SX300.jpg"},{"Title":"All Roads Lead to Rome","Year":"2015","imdbID":"tt4119278","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYwODU2MjkzNl5BMl5BanBnXkFtZTgwNDQyMTY2NzE@._V1_SX300.jpg"},{"Title":"When in Rome","Year":"2002","imdbID":"tt0324532","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjA0OGNiODItY2ExZC00ZDJjLTllMDctYTI4MTdlMDkxZDhkL2ltYWdlXkEyXkFqcGdeQXVyNTE4MzAyNDk@._V1_SX300.jpg"},{"Title":"Tony Rome","Year":"1967","imdbID":"tt0062380","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjBhOTQ2ZjAtNTY5Ny00YWUxLTgwZTItMzA4ODg2YWZkNmJkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg"},{"Title":"Ancient Rome: The Rise and Fall of an Empire","Year":"2006","imdbID":"tt0864944","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTgyMzk1MTIyM15BMl5BanBnXkFtZTcwNTc1MjY4Mw@@._V1_SX300.jpg"},{"Title":"Rome: Total War","Year":"2004","imdbID":"tt0373274","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BMmQ3MzJiNGYtOWRmYi00N2YzLTk3NDctZDg3ZDUxZGU5YjJiXkEyXkFqcGdeQXVyNDAzNzA0MzE@._V1_SX300.jpg"},{"Title":"Christmas in Rome","Year":"2019","imdbID":"tt10344956","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNWIzN2Q0MTItMmNmNC00M2JmLTliNmItYmNiODM5MjEyMTc2XkEyXkFqcGdeQXVyNTQ2NjI3NDQ@._V1_SX300.jpg"},{"Title":"Sabrina Goes to Rome","Year":"1998","imdbID":"tt0165456","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTQyNDU1NDkyOF5BMl5BanBnXkFtZTgwMTg2NTI2MTE@._V1_SX300.jpg"}]`);
    const expectedSortedByTitleMockingArray = JSON.parse(`[{"Title":"All Roads Lead to Rome","Year":"2015","imdbID":"tt4119278","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYwODU2MjkzNl5BMl5BanBnXkFtZTgwNDQyMTY2NzE@._V1_SX300.jpg"},{"Title":"Ancient Rome: The Rise and Fall of an Empire","Year":"2006","imdbID":"tt0864944","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTgyMzk1MTIyM15BMl5BanBnXkFtZTcwNTc1MjY4Mw@@._V1_SX300.jpg"},{"Title":"Christmas in Rome","Year":"2019","imdbID":"tt10344956","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNWIzN2Q0MTItMmNmNC00M2JmLTliNmItYmNiODM5MjEyMTc2XkEyXkFqcGdeQXVyNTQ2NjI3NDQ@._V1_SX300.jpg"},{"Title":"Rome","Year":"2005–2007","imdbID":"tt0384766","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BYTM4MmU1NWYtNzJjYy00YWFhLThjOGEtZmMxOGI1NzE0NGNiXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg"},{"Title":"Rome: Total War","Year":"2004","imdbID":"tt0373274","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BMmQ3MzJiNGYtOWRmYi00N2YzLTk3NDctZDg3ZDUxZGU5YjJiXkEyXkFqcGdeQXVyNDAzNzA0MzE@._V1_SX300.jpg"},{"Title":"Sabrina Goes to Rome","Year":"1998","imdbID":"tt0165456","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTQyNDU1NDkyOF5BMl5BanBnXkFtZTgwMTg2NTI2MTE@._V1_SX300.jpg"},{"Title":"To Rome with Love","Year":"2012","imdbID":"tt1859650","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTcwNTg4MDMxM15BMl5BanBnXkFtZTcwNjAzMzY3Nw@@._V1_SX300.jpg"},{"Title":"Tony Rome","Year":"1967","imdbID":"tt0062380","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjBhOTQ2ZjAtNTY5Ny00YWUxLTgwZTItMzA4ODg2YWZkNmJkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg"},{"Title":"When in Rome","Year":"2010","imdbID":"tt1185416","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTM0OTQ3MjgzN15BMl5BanBnXkFtZTcwMjMyNzg3Mg@@._V1_SX300.jpg"},{"Title":"When in Rome","Year":"2002","imdbID":"tt0324532","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjA0OGNiODItY2ExZC00ZDJjLTllMDctYTI4MTdlMDkxZDhkL2ltYWdlXkEyXkFqcGdeQXVyNTE4MzAyNDk@._V1_SX300.jpg"}]`);
    const expectedSortedByYearMockingArray = JSON.parse(`[{"Title":"Tony Rome","Year":"1967","imdbID":"tt0062380","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjBhOTQ2ZjAtNTY5Ny00YWUxLTgwZTItMzA4ODg2YWZkNmJkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg"},{"Title":"Sabrina Goes to Rome","Year":"1998","imdbID":"tt0165456","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTQyNDU1NDkyOF5BMl5BanBnXkFtZTgwMTg2NTI2MTE@._V1_SX300.jpg"},{"Title":"When in Rome","Year":"2002","imdbID":"tt0324532","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjA0OGNiODItY2ExZC00ZDJjLTllMDctYTI4MTdlMDkxZDhkL2ltYWdlXkEyXkFqcGdeQXVyNTE4MzAyNDk@._V1_SX300.jpg"},{"Title":"Rome: Total War","Year":"2004","imdbID":"tt0373274","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BMmQ3MzJiNGYtOWRmYi00N2YzLTk3NDctZDg3ZDUxZGU5YjJiXkEyXkFqcGdeQXVyNDAzNzA0MzE@._V1_SX300.jpg"},{"Title":"Rome","Year":"2005–2007","imdbID":"tt0384766","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BYTM4MmU1NWYtNzJjYy00YWFhLThjOGEtZmMxOGI1NzE0NGNiXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg"},{"Title":"Ancient Rome: The Rise and Fall of an Empire","Year":"2006","imdbID":"tt0864944","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTgyMzk1MTIyM15BMl5BanBnXkFtZTcwNTc1MjY4Mw@@._V1_SX300.jpg"},{"Title":"When in Rome","Year":"2010","imdbID":"tt1185416","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTM0OTQ3MjgzN15BMl5BanBnXkFtZTcwMjMyNzg3Mg@@._V1_SX300.jpg"},{"Title":"To Rome with Love","Year":"2012","imdbID":"tt1859650","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTcwNTg4MDMxM15BMl5BanBnXkFtZTcwNjAzMzY3Nw@@._V1_SX300.jpg"},{"Title":"All Roads Lead to Rome","Year":"2015","imdbID":"tt4119278","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYwODU2MjkzNl5BMl5BanBnXkFtZTgwNDQyMTY2NzE@._V1_SX300.jpg"},{"Title":"Christmas in Rome","Year":"2019","imdbID":"tt10344956","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNWIzN2Q0MTItMmNmNC00M2JmLTliNmItYmNiODM5MjEyMTc2XkEyXkFqcGdeQXVyNTQ2NjI3NDQ@._V1_SX300.jpg"}]`);
    it("sort by string field", () => {
      const sortedArray = filter(unsortedMockingArray,'Title');
      expect(JSON.stringify(sortedArray)).toMatch(JSON.stringify(expectedSortedByTitleMockingArray));
    })
    it("sort by number field", () => {
      const sortedArray = filter(unsortedMockingArray,'Year');      
      expect(JSON.stringify(sortedArray)).toMatch(JSON.stringify(expectedSortedByYearMockingArray));
    })
    
  })
})